version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "${LOCAL_DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wpnet
    restart: always
    container_name: "${PROJECT_NAME}_db"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${LOCAL_SERVER_PORT}:80"
    restart: always
    container_name: "${PROJECT_NAME}_wp"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./public:/var/www/html
    networks:
      - wpnet

  wpcli:
    image: wordpress:cli-2.3.0-php7.1
    volumes:
      - ./public:/var/www/html
    working_dir: /var/www/html
    container_name: "${PROJECT_NAME}_wpcli"
    networks:
      - wpnet

  wordmove:
    tty: true
    depends_on:
      - wordpress
    image: simonbland/wordmove
    restart: on-failure:5
    container_name: "${PROJECT_NAME}_wordmove"
    volumes:
      - ./config:/home/
      - ./public:/var/www/html
      - ~/.ssh:/home/.ssh
    networks:
      - wpnet
    environment:
      LOCAL_SERVER_PORT: "${LOCAL_SERVER_PORT}"
      PRODUCTION_URL: "${PRODUCTION_URL}"
      PRODUCTION_DIR_PATH: "${PRODUCTION_DIR_PATH}"
      PRODUCTION_DB_NAME: "${PRODUCTION_DB_NAME}"
      PRODUCTION_DB_USER: "${PRODUCTION_DB_USER}"
      PRODUCTION_DB_PASSWORD: "${PRODUCTION_DB_PASSWORD}"
      PRODUCTION_DB_HOST: "${PRODUCTION_DB_HOST}"
      PRODUCTION_DB_PORT: "${PRODUCTION_DB_PORT}"
      PRODUCTION_SSH_HOST: "${PRODUCTION_SSH_HOST}"
      PRODUCTION_SSH_USER: "${PRODUCTION_SSH_USER}"
      PRODUCTION_SSH_PORT: "${PRODUCTION_SSH_PORT}"

volumes:
  db_data: {}

networks:
      - wpnet
