version: '3.3'

services:
  db:
    image: mysql:5.7
    ports:
      - "${LOCAL_DB_PORT}:3306"
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    container_name: "${PROJECT_NAME}_db"
    environment:
      MYSQL_ROOT_PASSWORD: wordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - "${LOCAL_SERVER_PORT}:80"
    restart: always
    container_name: "${PROJECT_NAME}_wp"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./public:/var/www/html
volumes:
  db_data: {}